#!/bin/sh

sudo swapoff -a &&

echo -n "Input name of tomb key (without .key extension): " &&
read tombkey
echo -n "Input name of tomb file (without .tomb extension): " &&
read tombfile
echo -n "Input name of keepassxc database (without .kdbx extension): " &&
read kpname

tomb open -k ~/$tombkey.tomb.key ~/$tombfile.tomb &&
mv /media/$tombfile/.megarc ~/

megarm /Root/$kpname.kdbx.age
age -p ~/$kpname.kdbx > ~/$kpname.kdbx.age &&
megaput ~/$kpname.kdbx.age &&

echo -e "\033[31m Check MEGA directory"; tput setaf 50

megals

tput setaf 7

mv ~/.megarc /media/$tombfile/ &&
tomb close &&

echo -e "\033[31m We DID IT !"
